# checkov:skip=CKV_DOCKER_7: "Ensure the base image uses a non latest version tag"
# checkov:skip=CKV_DOCKER_2: "Ensure that HEALTHCHECK instructions have been added to container images"
FROM cgr.dev/chainguard/static:latest

WORKDIR /app

COPY show-and-tell /usr/local/bin/show-and-tell
COPY ui ./ui

USER nobody
EXPOSE 8080

ENTRYPOINT ["show-and-tell"]