---
#------------------------------------------------------------------------------
# Horizontal Pod Autoscaler
#------------------------------------------------------------------------------
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: show-and-tell
  labels:
    app.kubernetes.io/name: show-and-tell
    app.kubernetes.io/part-of: show-and-tell
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: show-and-tell
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
